### ISSUE TITLE
Manually add AnalogsEnhancer

### ISSUE THREAD

**Issue by Electric1447** [KuromeSan/cbps-db#158]
Please manually add https://github.com/Yoti/AnalogsEnhancer as the plugin is inside a zip archive

**Comment by KuromeSan** [comment]
Don

**Comment by Electric1447** [comment]
Please add the ability to add plugin in zip format, I have more like this

**Comment by KuromeSan** [comment]
mm you need to extract the plugin from the ZIP and upload somewhere (probably the cbpsdb gitlab mirror)

**Comment by Electric1447** [comment]
How?

**Comment by KuromeSan** [comment]
https://gitlab.com/SilicaAndPina/cbpsdb/-/tree/master/plugin
